// Copyright (c) 2016 Ez Entertainment SRL. All Rights Reserved.
// This code can only be used under the standard Unity Asset Store End User License Agreement
// A Copy of the EULA APPENDIX 1 is available at http://unity3d.com/company/legal/as_terms

// This partial class is Auto-Generated by the EzDataUtility

using UnityEngine;
using System.Collections.Generic;

namespace Ez.DataManager
{
    public partial class EzDataManager
    {
#pragma warning disable 0649

        #region Variable Examples
        public string CTGSTRT_0 = "Variable Examples";
        public bool soundOn;
        public float soundVolume;
        public bool musicOn;
        public float musicVolume;
        public readonly int CTGEND_0 = 4;
        #endregion

        #region Arrays Example
        public string CTGSTRT_1 = "Arrays Example";
        public string playerName;
        public long playerScore;
        public int[] levels;
        public readonly int CTGEND_1 = 3;
        #endregion

        #region Albert-Einstein
        public string CTGSTRT_2 = "Albert-Einstein";
        public string albertEinsteinName;
        public string albertEinsteinBirthDate;
        public Texture albertEinsteinCountryTexture;
        public Texture albertEinsteinImage;
        public string albertEinsteinQuote;
        public string albertEinsteinBio;
        public readonly int CTGEND_2 = 6;
        #endregion

        #region Europium
        public string CTGSTRT_3 = "Europium";
        public string europiumName;
        public string europiumSymbol;
        public int europiumAtomicNumber;
        public Texture europiumImage;
        public float europiumAtomicMass;
        public readonly int CTGEND_3 = 5;
        #endregion

        #region Getter/Setter Functions

        public static bool GetFloatByName(string varName, out float value)
        {
            value = 0f;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "soundVolume":
                    value = EzDataManager.Instance.soundVolume;
                    return true;
                case "musicVolume":
                    value = EzDataManager.Instance.musicVolume;
                    return true;
                case "europiumAtomicMass":
                    value = EzDataManager.Instance.europiumAtomicMass;
                    return true;
                default:
                    return false;
            }
        }

        public static bool SetFloatByName(string varName, float value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "soundVolume":
                    EzDataManager.Instance.soundVolume =  value ;
                    return true;
                case "musicVolume":
                    EzDataManager.Instance.musicVolume =  value ;
                    return true;
                case "europiumAtomicMass":
                    EzDataManager.Instance.europiumAtomicMass =  value ;
                    return true;
                default:
                    return false;
            }
        }

        public static bool GetIntByName(string varName, out int value)
        {
            value = 0;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "europiumAtomicNumber":
                    value = EzDataManager.Instance.europiumAtomicNumber;
                    return true;
                default:
                    return false;
            }
        }

        public static bool SetIntByName(string varName, int value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "europiumAtomicNumber":
                    EzDataManager.Instance.europiumAtomicNumber =  value ;
                    return true;
                default:
                    return false;
            }
        }

        public static bool GetBoolByName(string varName, out bool value)
        {
            value = false;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "soundOn":
                    value = EzDataManager.Instance.soundOn;
                    return true;
                case "musicOn":
                    value = EzDataManager.Instance.musicOn;
                    return true;
                default:
                    return false;
            }
        }

        public static bool SetBoolByName(string varName, bool value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "soundOn":
                    EzDataManager.Instance.soundOn =  value ;
                    return true;
                case "musicOn":
                    EzDataManager.Instance.musicOn =  value ;
                    return true;
                default:
                    return false;
            }
        }

        public static bool GetGameObjectByName(string varName, out GameObject value)
        {
            value = null;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool SetGameObjectByName(string varName, GameObject value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool GetStringByName(string varName, out string value)
        {
            value = string.Empty;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "playerName":
                    value = EzDataManager.Instance.playerName;
                    return true;
                case "albertEinsteinName":
                    value = EzDataManager.Instance.albertEinsteinName;
                    return true;
                case "albertEinsteinBirthDate":
                    value = EzDataManager.Instance.albertEinsteinBirthDate;
                    return true;
                case "albertEinsteinQuote":
                    value = EzDataManager.Instance.albertEinsteinQuote;
                    return true;
                case "albertEinsteinBio":
                    value = EzDataManager.Instance.albertEinsteinBio;
                    return true;
                case "europiumName":
                    value = EzDataManager.Instance.europiumName;
                    return true;
                case "europiumSymbol":
                    value = EzDataManager.Instance.europiumSymbol;
                    return true;
                default:
                    return false;
            }
        }

        public static bool SetStringByName(string varName, string value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "playerName":
                    EzDataManager.Instance.playerName =  value ;
                    return true;
                case "albertEinsteinName":
                    EzDataManager.Instance.albertEinsteinName =  value ;
                    return true;
                case "albertEinsteinBirthDate":
                    EzDataManager.Instance.albertEinsteinBirthDate =  value ;
                    return true;
                case "albertEinsteinQuote":
                    EzDataManager.Instance.albertEinsteinQuote =  value ;
                    return true;
                case "albertEinsteinBio":
                    EzDataManager.Instance.albertEinsteinBio =  value ;
                    return true;
                case "europiumName":
                    EzDataManager.Instance.europiumName =  value ;
                    return true;
                case "europiumSymbol":
                    EzDataManager.Instance.europiumSymbol =  value ;
                    return true;
                default:
                    return false;
            }
        }

        public static bool GetVector2ByName(string varName, out Vector2 value)
        {
            value = Vector2.zero;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool SetVector2ByName(string varName, Vector2 value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool GetVector3ByName(string varName, out Vector3 value)
        {
            value = Vector3.zero;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool SetVector3ByName(string varName, Vector3 value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool GetColorByName(string varName, out Color value)
        {
            value = Color.black;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool SetColorByName(string varName, Color value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool GetRectByName(string varName, out Rect value)
        {
            value = new Rect();
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool SetRectByName(string varName, Rect value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool GetMaterialByName(string varName, out Material value)
        {
            value = null;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool SetMaterialByName(string varName, Material value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool GetTextureByName(string varName, out Texture value)
        {
            value = null;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "albertEinsteinCountryTexture":
                    value = EzDataManager.Instance.albertEinsteinCountryTexture;
                    return true;
                case "albertEinsteinImage":
                    value = EzDataManager.Instance.albertEinsteinImage;
                    return true;
                case "europiumImage":
                    value = EzDataManager.Instance.europiumImage;
                    return true;
                default:
                    return false;
            }
        }

        public static bool SetTextureByName(string varName, Texture value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                case "albertEinsteinCountryTexture":
                    EzDataManager.Instance.albertEinsteinCountryTexture =  value ;
                    return true;
                case "albertEinsteinImage":
                    EzDataManager.Instance.albertEinsteinImage =  value ;
                    return true;
                case "europiumImage":
                    EzDataManager.Instance.europiumImage =  value ;
                    return true;
                default:
                    return false;
            }
        }

        public static bool GetQuaternionByName(string varName, out Quaternion value)
        {
            value = Quaternion.identity;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool SetQuaternionByName(string varName, Quaternion value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool GetObjectByName(string varName, out Object value)
        {
            value = null;
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool SetObjectByName(string varName, Object value)
        {
            if(string.IsNullOrEmpty(varName)) return false;
            switch(varName)
            {
                default:
                    return false;
            }
        }

        public static bool GetArrayByName(string arrayName, out System.Array array)
        {
            array = null;
            if(string.IsNullOrEmpty(arrayName)) return false;
            switch(arrayName)
            {
                case "levels":
                    array = EzDataManager.Instance.levels;
                    return true;
                default:
                    return false;
            }
        }

        public static bool SetArrayByName(string arrayName, System.Array array)
        {
            if(string.IsNullOrEmpty(arrayName)) return false;
            try
            {
                switch(arrayName)
                {
                case "levels":
                    System.Array.Resize(ref EzDataManager.Instance.levels, array.Length);
                    System.Array.Copy(array, EzDataManager.Instance.levels, array.Length);
                    return true;
                    default:
                        return false;
                }
            }
            catch(System.Exception)
            {
                return false;
            } 
        }
        #endregion //Getter/Setter Functions

#pragma warning restore 0649
    }
}